name: Build and Test Flutter App

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Test web build
      run: flutter build web --dart-define=LIFF_ID=test-liff-id
      env:
        LIFF_ID: test-liff-id

    - name: Test Android build
      run: flutter build apk --dart-define=LIFF_ID=test-liff-id
      env:
        LIFF_ID: test-liff-id
        path: build/app/outputs/flutter-apk/app-release.apk
